In [1]:
typeof("String")

String

In [3]:
typeof("111")

String

In [4]:
typeof('2')

Char

In [7]:
'H'

'H': ASCII/Unicode U+0048 (category Lu: Letter, uppercase)

In [8]:
"\U0048"

"H"

In [15]:
println("γβα⋄♢π∑")

γβα⋄♢π∑


In [16]:
typeof(true)

Bool

In [17]:
2.0==2

true

In [28]:
1.999999999999999==2

false

In [29]:
2< 3/2

false

## Array types

In [33]:
Array{Any}(undef, 3)

3-element Array{Any,1}:
 #undef
 #undef
 #undef

In [35]:
a = Array{String}(undef, 3)

3-element Array{String,1}:
 #undef
 #undef
 #undef

In [41]:
a[1] = "223"
a

3-element Array{String,1}:
    "223"
 #undef  
 #undef  

In [45]:
人 = 123
生 = 321

321

In [44]:
println(人)

123


In [48]:
w = [人, 生]

2-element Array{Int64,1}:
 123
 321

In [49]:
size(w)

(2,)

In [56]:
w = reshape(w, (2, 1))

2×1 Array{Int64,2}:
 123
 321

In [59]:
(m, n)=size(w)

(2, 1)

In [63]:
typeof(m)

Int64

In [67]:
?===

search: === == !==



```
===(x,y) -> Bool
≡(x,y) -> Bool
```

Determine whether `x` and `y` are identical, in the sense that no program could distinguish them. First the types of `x` and `y` are compared. If those are identical, mutable objects are compared by address in memory and immutable objects (such as numbers) are compared by contents at the bit level. This function is sometimes called "egal". It always returns a `Bool` value.

# Examples

```jldoctest
julia> a = [1, 2]; b = [1, 2];

julia> a == b
true

julia> a === b
false

julia> a === a
true
```


In [69]:
'a'=="a" 

false

In [70]:
x = Array{Int64}(undef,11, 12) 

11×12 Array{Int64,2}:
 0  1  0  3  2  1  0  0  0  1  2  1
 2  1  0  1  1  1  1  0  1  1  1  1
 2  1  1  2  0  1  0  1  0  1  1  1
 0  0  2  0  0  0  0  0  0  1  1  0
 0  2  0  2  1  2  2  1  0  1  0  0
 2  1  0  0  1  1  1  1  1  3  1  0
 1  1  0  0  1  0  0  1  1  0  0  0
 0  1  0  2  1  0  1  0  1  0  1  0
 0  0  2  2  1  1  1  0  1  2  1  0
 1  2  1  0  0  2  0  1  1  1  1  0
 1  1  2  0  2  0  1  0  1  1  0  0

In [74]:
typeof(x)

Array{Int64,2}

In [82]:
typeof(Cake)

Int64

In [84]:
a=Array{Float64, 3}

Array{Float64,3}

In [88]:
a = Array{Integer,2}(undef, 2, 3)

2×3 Array{Integer,2}:
 #undef  #undef  #undef
 #undef  #undef  #undef